apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store  # 這個名字必須跟 ExternalSecret 裡的 ref 名字一樣！
spec:
  provider:
    gcpsm: # Google Cloud Platform Secret Manager
      projectID: etl-demo-482811
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-store-creds  # 對應第二步建立的 Secret 名稱
            key: secret-access-credentials # 對應第二步 --from-file 的 key
            namespace: external-secrets # 關鍵！告訴它那把鑰匙放在哪個 NS