apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  sources:
    # 1) Helm chart source
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 80.10.0
      helm:
        valueFiles:
          - $values/k8s/values/monitoring/base.yaml
          - $values/k8s/values/monitoring/dev.yaml

    # 2) Git repo that hosts values
    - repoURL: https://github.com/HarrisonZz/GCP-GKE-ETL-DEMO
      path: k8s/values/monitoring
      targetRevision: main
      ref: values

    - repoURL: https://github.com/HarrisonZz/GCP-GKE-ETL-DEMO
      targetRevision: main
      # 請確認您的 SecretStore 和 ExternalSecret YAML 確實放在這個路徑下
      path: k8s/eso

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
